import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Button } from "@/components/ui/button";
import { Wallet } from "lucide-react";
import "./globals.css";
//import styles from "./ui/home.module.css";
import NavBar from "./ui/components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-neutral-900`}
      >
        {/*<section className="flex flex-col">
          {children}
          <div className="bg-gray-500 h-20"></div>
          
        </section>
        <div className="h-20"></div>*/}
        
        <div className="absolute top-0 left-0 flex justify-center items-center w-full px-5 py-5">
          <Button className="rounded-full bg-[#0a6320] hover:bg-[#0a6320]/80 h-9 px-4 py-2 hover:cursor-pointer">
            <Wallet></Wallet>
            Connect Wallet
          </Button>
        </div>
        <main className="flex min-h-screen px-5 sm:px-20 py-14 bg-neutral-900">
          {children}
        </main>
        <NavBar></NavBar>
      </body>
    </html>
  );
}
